name: Build Project
permissions:
  contents: read
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: make build
      - name: Test
        run: make test
